### ISSUE TITLE
Add alias for @job-it/react/src folder

### ISSUE THREAD

**Issue by alnavarrop99** [el-frontend/job-it-be-challenge#3]
Currently, we are using long and complex import paths that can make the code difficult to read and maintain. By using aliases, we can simplify the import paths and make the code cleaner and easier to manage.

In more than two levels, I see it as quite justified.

## Examples: 
**`/apps/react/src/main.tsx b/apps/react/src/main.tsx`**
```tsx
-import App from "./App.tsx";
-import "./assets/styles/index.css";
// --- after
+import App from "@/App.tsx";
+import "@/assets/styles/index.css"
```
----
**`/apps/react/src/modules/jobs/components/job-filters/JobFiltersForm.tsx`**
```tsx
-import RHFMultiRangeSliderField from "../../../../core/components/form/rhf/RHFMultiRangeSliderField";
-import RHFSelectField from "../../../../core/components/form/rhf/RHFSelectField";
-import RHFTextField from "../../../../core/components/form/rhf/RHFTextField";
// --- after: 
+import RHFMultiRangeSliderField from "@/core/components/form/rhf/RHFMultiRangeSliderField";
+import RHFSelectField from "@/core/components/form/rhf/RHFSelectField";
+import RHFTextField from "@/core/components/form/rhf/RHFTextField";

 import JobFilterInput from "./JobFilterInput";
```

**Comment by el-frontend** [comment]
Thanks for the pull request! It has already been merged. Thank you! 🎉

**Comment by el-frontend** [comment]
Thanks for the pull request! It has already been merged. Thank you! 🎉
